backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

editor:
  preview: false

collections:
  - name: "blog"
    label: "صحف"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "الصورة", name: "thumbnail", widget: "image", required: false }
      - { label: "تاريخ النشر", name: "date", widget: "datetime" }
      - { label: "المقالة", name: "body", widget: "markdown" }
  - name: "TV"
    label: "مقابلات"
    folder: "src/pages/TV"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "TV-post", required: false }
      - { label: "العنوان", name: "title", widget: "string", required: false }
      - { label: "المحتوى", name: "body", widget: "markdown", required: false }
  - name: "surgeries"
    label: "العمليات الجراحية"
    folder: "src/pages/surgeries"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "surgery-post", required: false }
      - { label: "العنوان", name: "title", widget: "string", required: true }
      - { label: "تاريخ النشر", name: "date", format: "MM-DD-YYYY h:mm a", widget: "datetime", required: true }
      - { label: "الصورة", name: "img", widget: "image", required: true }
      - { label: "المحتوى", name: "body", widget: "markdown", required: true }
  - name: "pages"
    label: "باقي الصفحات"
    files:
      - file: "src/content/Contact/index.md"
        label: "حجز الموعد"
        name: "contact"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page" }
          - label: "الأوقات المتاحة للحجز   | يرجى كتابة الأوقات بنظام الـ24 ساعة "
            name: "availableTime"
            widget: "object"
            fields:
              - label: "يبدى الدوام عند الساعة : "
                name: "startTime"
                widget: "number"
                default: 0
                valueType: "int"
                min: 0
                max: 24
                required: true
              - label: "ينتهي الدوام عند الساعة :"
                name: "endTime"
                widget: "number"
                default: 0
                valueType: "int"
                min: 0
                max: 24
                required: true
          - label: "أيام الدوام "
            name: "days"
            widget: "object"
            fields:
              - { label: "السبت", name: "sat", widget: "boolean", default: false, required: true }
              - { label: "الأحد", name: "sun", widget: "boolean", default: false, required: true }
              - { label: "الأثنين", name: "mon", widget: "boolean", default: false, required: true }
              - { label: "الثلاثاء", name: "tue", widget: "boolean", default: false, required: true }
              - { label: "الأربعاء", name: "wed", widget: "boolean", default: false, required: true }
              - { label: "الخميس", name: "thu", widget: "boolean", default: false, required: true }
              - { label: "الجمعة", name: "fri", widget: "boolean", default: false, required: true }
          - { label: "رقم الجوال الذي ستأتي له رسالة الحجز", name: "phone", widget: "string" }
      - file: "src/content/CV/index.md"
        label: "السيرة الذاتية"
        name: "cv"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "cv-page" }
          - { label: "path", name: "path", widget: "hidden", default: "/cv", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
